export const PHRASES = [
  "Está para unos Nothing Else Matters",
  "Estoy para unos Matthew McConaughey",
  "Sale un Amargovich?",
  "Hoy salen unos Matthew Perry",
  "Hacete un el Mateó a un Policía Motorizado",
  "Hago unos Maturkish Airlines",
  "Juega Mateos Messi?",
  "Armate unos Chotto Matte",
  "Esta para unos Amateurs",
  "Esperáme con esos Matienzos",
  "Me hago unos partido de la Matanza",
  "Hago unos Materiales",
  "Tomamos unos Lucas Matthysse?",
  "Juega unos Materazzi?",
  "Hago unos Matorrales",
  "Salen unos Matt Groening?",
  "Ahí me armo unos Leo Mattioli",
  "Me armo unos Matemáticos",
  "Salen esos Matusalén?",
  "Sale un Matarazzo",
  "Salen unos Amargos?",
  "Hago unos Juegos Olimpicos de Matenas 2004",
  "Hago unos Matecnicos",
  "Me armo un Matt Le Blanc",
  "Esta para unos Verdolagas",
  "Salen unos Matt Damon",
  "Estoy para unos Matesaurios",
  "Hago unos Materapia cognitiva-conductual",
  "Me armo unos Amaterasu",
  "Salen unos Verdes?",
  "Gestionando esos Jaque Mate",
  "Esta para un Matute",
  "Hacete unos Maste Vale",
  "Sale unos Matados?",
  "Me armo unos Mathelma & Louise y estoy",
  "Juega Matuidi?",
  "Unos Materminal de omnibus de Mar del Plata",
  "Salen unos Mátines",
  "Sale un matine",
  "Hacete unos lavados",
];
